services:
  api1: &api
    image: ruby
    volumes:
      - .:/app
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
    working_dir: /app
    command: bash -c "bundle install && ruby server.rb"
    environment:
      - DB_HOST=postgres
      - RUBY_YJIT_ENABLE=1

  api2:
    <<: *api

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 9999:9999
    depends_on:
      - api1
      - api2
