services:
  api1: &api
    container_name: api1
    image: ruby:3.3.0
    volumes:
      - .:/app
    working_dir: /app
    command: bash -c "bundle install && ruby server.rb"
    environment:
      - RUBY_YJIT_ENABLE=1
      - PORT=3001
    network_mode: host

  api2: 
    <<: *api
    container_name: api2
    environment:
      - RUBY_YJIT_ENABLE=1
      - PORT=3002
    network_mode: host

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999" 
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

  db:
    container_name: postgres
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports:
      - "5432:5432"
    volumes:
      - ./script.sql:/docker-entrypoint-initdb.d/script.sql
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

volumes:
  rubygems: