worker_processes 1;

events {
	worker_connections 16384;
}

http {
	access_log off;

	upstream api {
		server api1:3000;
		server api2:3000;
	}

	server {
		listen 9999 backlog=4096;

		location / {
			proxy_pass http://api;
		}
	}
}
